name: Automation tests

on: [ push ]

jobs:
    chrome-test:
        name: Run tests on Chrome
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Node.js
            uses: actions/setup-node@v4

          - name: Install dependencies
            run: npm ci

          - name: Install Playwright Browsers
            run: npx playwright install --with-deps

          - name: Run Chrome tests
            run: npx codeceptjs run-multiple desktop:chromium --steps
            env: 
                HEADLESS: true

          - name: Allure report
            if: always()
            run: npx allure-commandline generate output/allure-results --clean -o output/allure-report

          - name: Upload visual test report
            uses: actions/upload-artifact@v4
            if: always()
            with:
                name: chrome-report
                path: output/allure-report

    firefox-test:
        name: Run tests on Firefox
        runs-on: ubuntu-latest
        container:
            image: mcr.microsoft.com/playwright:v1.54.1-jammy

        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          
          - name: Set up Node.js
            uses: actions/setup-node@v4
          
          - name: Install dependencies
            run: npm ci

          - name: Run Firefox tests
            run: npx codeceptjs run-multiple desktop:firefox --steps
            env: 
                 HEADLESS: true
                 HOME: /root
                 
          - name: Upload artifacts
            uses: actions/upload-artifact@v4
            if: always()
            with:
                name: firefox-report
                path: output/
    
    safari-test:
        name: Run tests on Safari
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4
         
          - name: Set up Node
            uses: actions/setup-node@v4
        
          - name: Install dependencies
            run: npm ci

          - name: Install Playwright browsers
            run: npx playwright install --with-deps
        
          - name: Run Safari tests
            run: npx codeceptjs run-multiple desktop:webkit --steps
            env: 
                HEADLESS: true

          - name: Upload artifacts
            uses: actions/upload-artifact@v4
            if: always()
            with:
                name: safari-report
                path: output/

    
      






